trigger: main
version: '3'

services:
  web:
    image: nginx
    ports:
      - "80"
    networks:
      - azure

networks:
  azure:
    driver: azure
    driver_opts:
      azure_client_id: YOUR_AZURE_CLIENT_ID
      azure_client_secret: YOUR_AZURE_CLIENT_SECRET
      azure_subscription_id: YOUR_AZURE_SUBSCRIPTION_ID
      azure_tenant_id: YOUR_AZURE_TENANT_ID
